version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: always
    networks:
    - backend

  api:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '4500:4500'
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_MAIN_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_MAIN_PASS
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
